# Generated by Django 6.0.6 on 2026-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('calculation_type', models.CharField(max_length=50)),
                ('input_value', models.FloatField()),
                ('recommended_kw', models.FloatField()),
                ('monthly_savings', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
